import type { Metadata } from "next";
import { PolicyPage, type PolicySection } from "@/components/PolicyPage";
import { buildPageMetadata } from "@/lib/metadata";

export const metadata: Metadata = buildPageMetadata("Privacy Policy | Swabhiman Foundation", "How Swabhiman Foundation collects, uses and safeguards information provided through this website.", "/privacy-policy");

const sections: PolicySection[] = [
  { id: "scope", title: "1. Scope", content: <p>This policy explains how Swabhiman Jan Evam Pashu Kalyan Foundation handles personal information submitted through this website, including contact enquiries and online donations. It does not cover independent websites or services linked from our pages.</p> },
  { id: "information", title: "2. Information we collect", content: <><p>Depending on how you use the website, we may receive:</p><ul><li>Name, email address, mobile number, subject and message when you contact us.</li><li>Donor name, email, mobile number, donation amount, selected cause and payment reference.</li><li>Optional address, message or PAN where the donor chooses to provide it for an applicable record or receipt need.</li><li>Limited technical information used for security, spam prevention and service reliability, such as IP address, request time and browser-provided data.</li></ul><p>We do not ask for or store complete card details, CVV, UPI PIN, banking password or OTP. Payment credentials are entered into the payment gateway’s hosted checkout.</p></> },
  { id: "use", title: "3. How information is used", content: <><p>We use information to:</p><ul><li>Respond to enquiries and requests to volunteer or partner.</li><li>Create, verify and acknowledge donations.</li><li>Prevent abuse, fraud and automated spam.</li><li>Meet lawful accounting, governance and regulatory requirements.</li><li>Improve the accessibility, safety and reliability of the website.</li></ul><p>We do not sell personal information.</p></> },
  { id: "sharing", title: "4. Service providers and sharing", content: <p>Information may be processed by service providers that support payment processing, email delivery, website hosting, security or professional compliance. We share only what is reasonably necessary for the service. Information may also be disclosed where required by law, a competent authority or to protect legitimate legal rights.</p> },
  { id: "payments", title: "5. Payment information", content: <p>Online donations use Razorpay-compatible hosted checkout and server-side verification. The gateway processes payment instruments under its own privacy and security terms. The foundation receives transaction references, payment status and limited donor details needed to verify and acknowledge the contribution.</p> },
  { id: "retention", title: "6. Retention and security", content: <p>We retain personal information only for as long as reasonably needed for the stated purpose, legal record-keeping, dispute resolution and security. We use proportionate administrative and technical safeguards, but no internet transmission or storage method can be guaranteed to be completely secure.</p> },
  { id: "choices", title: "7. Your choices", content: <p>You may ask us to review or correct information you submitted, or request deletion where retention is not required by law or legitimate record-keeping needs. To protect privacy, we may need to verify the requester’s identity and transaction or enquiry details.</p> },
  { id: "children", title: "8. Children’s privacy", content: <p>This website is intended for general information and adult-supported engagement. A child should not submit personal or payment information without the involvement of a parent or lawful guardian.</p> },
  { id: "changes", title: "9. Policy changes", content: <p>We may update this policy as services, legal requirements or operating practices change. The current version and update date will be published on this page.</p> },
];

export default function PrivacyPolicyPage() { return <PolicyPage title="Privacy Policy" summary="A clear account of what information this website collects, why it is needed and how it is handled." sections={sections} />; }
